@StudentExchangeBck_HostAddress = http://localhost:5239

GET {{StudentExchangeBck_HostAddress}}/Schools/
Accept: application/json

POST {{StudentExchangeBck_HostAddress}}/Register/
Accept: application/json

POST {{StudentExchangeBck_HostAddress}}/LogIn/
Accept: application/json
###
